pipeline {

    agent any

    parameters {
        string(name: 'TERRAFORM_MODULE', description: 'Inserte la ruta del modulo de terraform.')
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Aprobar automaticamente.')
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Seleccione la accion a realizar.')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }

    stages {
        stage('Configurando Terraform') {
            steps {
                script {
                    sh 'terraform --version'
                    sh 'ls -lt $WORKSPACE/$TERRAFORM_MODULE'
                    sh 'ls -lt'
                }
            }
        }
        stage('Iniciando Módulo de Terraform') {
            steps {
                script {
                    sh 'terraform -chdir=$WORKSPACE/$TERRAFORM_MODULE init'
                }
            }
        }
        stage('Imprimiendo Plan') {
            steps {
                sh 'terraform -chdir=$WORKSPACE/$TERRAFORM_MODULE plan'
            }
        }
        stage('Aplicando Terraform Apply / Destroy') {
            steps {
                script {
                    if (params.action == 'apply') {
                        if (!params.autoApprove) {
                            input message: "¿Desea aplicar los cambios?",
                        }

                        sh 'terraform -chdir=$WORKSPACE/$TERRAFORM_MODULE ${action} -input=false tfplan'

                    } else if (params.action == 'destroy') {
                        if (!params.autoApprove) {
                            input message: "¿Desea eliminar los recursos?",
                        }

                        sh 'terraform -chdir=$WORKSPACE/$TERRAFORM_MODULE ${action} --auto-approve'

                    } else {
                        error "Acción invalida, por favor seleccione apply o destroy."
                    }
                }
            }
        }
    }
}