pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    parameters {
        string(name: 'TERRAFORM_MODULE', description: 'Inserte la ruta del modulo de terraform')
    }

    stages {
        stage('Configurando Terraform') {
            steps {
                script {
                    sh 'terraform --version'
                    sh 'pwd'
                    sh 'ls -lt $WORKSPACE/$TERRAFORM_MODULE'
                    sh 'cd $WORKSPACE/$TERRAFORM_MODULE'
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Deplegando Modulo de Terraform') {
            steps {
                script {
                    sh 'echo Hello Step 2'
                    // sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }
}